apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app1.name }}
spec:
  replicas: {{ .Values.app1.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app1.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app1.name }}
    spec:
      containers:
      - name: {{ .Values.app1.name }}
        image: {{ .Values.app1.image.repository }}:{{ .Values.app1.image.tag }}
        ports:
        - containerPort: {{ .Values.app1.port }}
        
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app2.name }}
spec:
  replicas: {{ .Values.app2.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app2.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app2.name }}
    spec:
      containers:
      - name: {{ .Values.app2.name }}
        image: {{ .Values.app2.image.repository }}:{{ .Values.app2.image.tag }}
        ports:
        - containerPort: {{ .Values.app2.port }}