apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.app1.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app1.name }}
            port: 
              number: {{ .Values.app1.port }}
      - path: {{ .Values.app2.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app2.name }}
            port:
              number: {{ .Values.app2.port }}