apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app1.name }}
spec:
  selector:
    app: {{ .Values.app1.name }}
  ports:
  - port: {{ .Values.app1.port }}
    targetPort: {{ .Values.app1.port }}
    
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app2.name }}
spec:
  selector:
    app: {{ .Values.app2.name }}
  ports:
  - port: {{ .Values.app2.port }}
    targetPort: {{ .Values.app2.port }}